const express = require("express")
const router = express.Router()
const controller = require("../controller/Stu_course.controller")
const AuthenticationST = require("../middleware/AuthenticationST")
const AuthenticationTea = require("../middleware/AuthenticationTea")
const checkoverlapping = require("../middleware/checkoverlapping ")
router.get("/Getstudentcourse",AuthenticationST,controller.GetstudentCourse)
router.get("/GetStudent/:id",AuthenticationST,controller.GetStudent)
router.get("/GetscheduleStudent", AuthenticationST,controller.GetscheduleStudent)
router.post("/registerstudencourse",AuthenticationST,checkoverlapping,controller.registerstudencourse)
router.patch("/editstatus",AuthenticationTea,controller.editstatus)
module.exports = router
