const express = require("express")
const router = express.Router()
const controller = require("../controller/User.controller")
const AuthenticationST = require("../middleware/AuthenticationST")
router.get("/Getdetail",AuthenticationST,controller.Getdetail)
router.post("/Post/student",controller.Post)
router.post("/Post/teacher",controller.PostTeacher)
router.post("/login",controller.login)
router.post("/confirmOTP", AuthenticationST,controller.ConfirmOTP)
module.exports = router
