const express = require("express");
const router = express.Router();
const controller = require("../controller/User.controller");
const authenticationStudent = require("../middleware/authenticationStudent");
router.get("/Getdetail", authenticationStudent, controller.Getdetail);
router.post("/Post/student", controller.Post);
router.post("/Post/teacher", controller.PostTeacher);
router.post("/login", controller.login);
router.post("/confirmOTP", authenticationStudent, controller.ConfirmOTP);
module.exports = router;
